"""add_client_and_relations

Revision ID: 1df92cd113ed
Revises: 2fe6cfe8840d
Create Date: 2026-06-24 19:28:35.952103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1df92cd113ed'
down_revision: Union[str, None] = '2fe6cfe8840d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('whatsapp', sa.String(length=20), nullable=False),
    sa.Column('consent_whatsapp', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_index(op.f('ix_clients_whatsapp'), 'clients', ['whatsapp'], unique=True)
    op.add_column('accounts_receivable', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'accounts_receivable', 'clients', ['client_id'], ['id'])
    op.add_column('catalog_leads', sa.Column('client_id', sa.Integer(), nullable=True))
    op.add_column('catalog_leads', sa.Column('contatado', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.create_foreign_key(None, 'catalog_leads', 'clients', ['client_id'], ['id'])
    op.add_column('sales', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sales', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###

    # Lógica customizada de migração de dados históricos para popular a base de clientes unificada
    bind = op.get_bind()
    
    # Busca todos os leads distintos agrupados por whatsapp
    # No PostgreSQL, DISTINCT ON (whatsapp) funciona perfeitamente.
    # No SQLite (se usado localmente), fazemos um fallback caso dê erro de sintaxe, ou escrevemos uma query compatível.
    # Como a VPS de teste e produção usam PostgreSQL e local pode usar SQLite, podemos tentar usar GROUP BY ou subquery simples.
    # Query compatível com ambos:
    query = """
        SELECT l.nome, l.whatsapp, l.consent, l.created_at 
        FROM catalog_leads l
        WHERE l.id IN (
            SELECT MIN(id) 
            FROM catalog_leads 
            GROUP BY whatsapp
        )
    """
    leads = bind.execute(sa.text(query)).fetchall()
    
    for row in leads:
        nome = row[0] if row[0] else "Cliente sem nome"
        whatsapp = row[1]
        consent = row[2]
        created_at = row[3]
        
        bind.execute(
            sa.text(
                "INSERT INTO clients (nome, whatsapp, consent_whatsapp, created_at, updated_at) "
                "VALUES (:nome, :whatsapp, :consent_whatsapp, :created_at, :updated_at) "
                "ON CONFLICT (whatsapp) DO NOTHING"
            ),
            {"nome": nome, "whatsapp": whatsapp, "consent_whatsapp": consent, "created_at": created_at, "updated_at": created_at}
        )
        
    # Atualiza as FKs de catalog_leads
    bind.execute(sa.text("""
        UPDATE catalog_leads cl
        SET client_id = c.id
        FROM clients c
        WHERE cl.whatsapp = c.whatsapp
    """))
    
    # Atualiza a coluna contatado baseado no histórico de contatos
    bind.execute(sa.text("""
        UPDATE catalog_leads cl
        SET contatado = TRUE
        WHERE EXISTS (
            SELECT 1 
            FROM client_contact_histories h 
            WHERE h.whatsapp = cl.whatsapp
        )
    """))
    
    # Opcional: Associar contas a receber por correspondência de nome
    bind.execute(sa.text("""
        UPDATE accounts_receivable ar
        SET client_id = c.id
        FROM clients c
        WHERE ar.cliente = c.nome
    """))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_column('sales', 'client_id')
    op.drop_constraint(None, 'catalog_leads', type_='foreignkey')
    op.drop_column('catalog_leads', 'contatado')
    op.drop_column('catalog_leads', 'client_id')
    op.drop_constraint(None, 'accounts_receivable', type_='foreignkey')
    op.drop_column('accounts_receivable', 'client_id')
    op.drop_index(op.f('ix_clients_whatsapp'), table_name='clients')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
