"""add_client_contact_history

Revision ID: 2fe6cfe8840d
Revises: 009
Create Date: 2026-06-23 23:01:31.823923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2fe6cfe8840d'
down_revision: Union[str, None] = '009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_contact_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('whatsapp', sa.String(length=20), nullable=False),
    sa.Column('mensagem', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_contact_histories_id'), 'client_contact_histories', ['id'], unique=False)
    op.create_index(op.f('ix_client_contact_histories_whatsapp'), 'client_contact_histories', ['whatsapp'], unique=False)
    op.drop_index(op.f('ix_agent_chat_memory_id'), table_name='agent_chat_memory')
    op.drop_index(op.f('ix_agent_chat_memory_scope'), table_name='agent_chat_memory')
    op.drop_index(op.f('ix_agent_chat_memory_user_id'), table_name='agent_chat_memory')
    op.drop_index(op.f('ix_agent_chat_memory_user_scope_created'), table_name='agent_chat_memory')
    op.drop_table('agent_chat_memory')
    op.drop_index(op.f('ix_personal_agenda_id'), table_name='personal_agenda')
    op.drop_index(op.f('ix_personal_agenda_user_id'), table_name='personal_agenda')
    op.drop_table('personal_agenda')
    op.drop_index(op.f('ix_user_cart_items_id'), table_name='user_cart_items')
    op.drop_index(op.f('ix_user_cart_items_product_id'), table_name='user_cart_items')
    op.drop_index(op.f('ix_user_cart_items_user_id'), table_name='user_cart_items')
    op.drop_table('user_cart_items')
    op.drop_index(op.f('ix_agent_prompts_id'), table_name='agent_prompts')
    op.drop_index(op.f('ix_agent_prompts_key'), table_name='agent_prompts')
    op.drop_table('agent_prompts')
    op.alter_column('sales', 'subtotal_bruto',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.create_foreign_key(None, 'sales', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.alter_column('sales', 'subtotal_bruto',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.create_table('agent_prompts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('key', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_prompts_pkey'))
    )
    op.create_index(op.f('ix_agent_prompts_key'), 'agent_prompts', ['key'], unique=True)
    op.create_index(op.f('ix_agent_prompts_id'), 'agent_prompts', ['id'], unique=False)
    op.create_table('user_cart_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('user_cart_items_product_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_cart_items_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_cart_items_pkey')),
    sa.UniqueConstraint('user_id', 'product_id', name=op.f('uq_user_cart_user_product'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_user_cart_items_user_id'), 'user_cart_items', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_cart_items_product_id'), 'user_cart_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_user_cart_items_id'), 'user_cart_items', ['id'], unique=False)
    op.create_table('personal_agenda',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('titulo', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('data', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('hora', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('personal_agenda_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('personal_agenda_pkey'))
    )
    op.create_index(op.f('ix_personal_agenda_user_id'), 'personal_agenda', ['user_id'], unique=False)
    op.create_index(op.f('ix_personal_agenda_id'), 'personal_agenda', ['id'], unique=False)
    op.create_table('agent_chat_memory',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('scope', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('extra_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('agent_chat_memory_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_chat_memory_pkey'))
    )
    op.create_index(op.f('ix_agent_chat_memory_user_scope_created'), 'agent_chat_memory', ['user_id', 'scope', 'created_at'], unique=False)
    op.create_index(op.f('ix_agent_chat_memory_user_id'), 'agent_chat_memory', ['user_id'], unique=False)
    op.create_index(op.f('ix_agent_chat_memory_scope'), 'agent_chat_memory', ['scope'], unique=False)
    op.create_index(op.f('ix_agent_chat_memory_id'), 'agent_chat_memory', ['id'], unique=False)
    op.drop_index(op.f('ix_client_contact_histories_whatsapp'), table_name='client_contact_histories')
    op.drop_index(op.f('ix_client_contact_histories_id'), table_name='client_contact_histories')
    op.drop_table('client_contact_histories')
    # ### end Alembic commands ###
