"""add_stock_adjustments

Revision ID: 3ae4b7c8df9e
Revises: e7ad6f6c9afd
Create Date: 2026-06-30 20:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ae4b7c8df9e'
down_revision: Union[str, None] = 'e7ad6f6c9afd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'stock_adjustments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('product_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('quantidade_anterior', sa.Float(), nullable=False),
        sa.Column('quantidade_nova', sa.Float(), nullable=False),
        sa.Column('diferenca', sa.Float(), nullable=False),
        sa.Column('motivo', sa.String(length=50), nullable=False),
        sa.Column('observacao', sa.String(length=200), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_adjustments_id'), 'stock_adjustments', ['id'], unique=False)
    op.create_index(op.f('ix_stock_adjustments_product_id'), 'stock_adjustments', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_adjustments_user_id'), 'stock_adjustments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_adjustments_user_id'), table_name='stock_adjustments')
    op.drop_index(op.f('ix_stock_adjustments_product_id'), table_name='stock_adjustments')
    op.drop_index(op.f('ix_stock_adjustments_id'), table_name='stock_adjustments')
    op.drop_table('stock_adjustments')
    # ### end Alembic commands ###
