"""add_client_origem

Revision ID: e7ad6f6c9afd
Revises: 1df92cd113ed
Create Date: 2026-06-24 20:08:26.894743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""add_client_origem

Revision ID: e7ad6f6c9afd
Revises: 1df92cd113ed
Create Date: 2026-06-24 20:08:26.894743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7ad6f6c9afd'
down_revision: Union[str, None] = '1df92cd113ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('origem', sa.String(length=20), nullable=False, server_default='local'))
    # ### end Alembic commands ###

    bind = op.get_bind()
    bind.execute(sa.text("""
        UPDATE clients
        SET origem = 'catalogo'
        WHERE id IN (SELECT DISTINCT client_id FROM catalog_leads WHERE client_id IS NOT NULL)
    """))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'origem')
    # ### end Alembic commands ###
